ConnectFlow.UI/Controllers/CountriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ServiceContracts;
using Services;

namespace CRUDExample.Controllers
{
  [Route("[controller]")]
  public class CountriesController : Controller
  {
    private readonly ICountriesUploaderService _countriesService;

    public CountriesController(ICountriesUploaderService countriesService)
    {
      _countriesService = countriesService;
    }
    [HttpGet]
    [Route("[action]")]
    [Authorize(Roles = "Admin")]
    public IActionResult UploadFromExcel()
    {
      return View();
    }
    [HttpPost]
    [Route("[action]")]
    [Authorize(Roles = "Admin")]
    public async Task< IActionResult> UploadFromExcel( IFormFile excelfile)
    {
      if (excelfile == null||excelfile.Length==0)
      {
        ViewBag.ErrorMessage = "Please select xlsx file";
        return View();
        
      }
      if (!Path.GetExtension(excelfile.FileName).Equals(".xlsx", StringComparison.OrdinalIgnoreCase))
      {
        ViewBag.ErrorMessage = "Unsupported file. 'xlsx' is expected";
        return View();
      }
     int countriesCountInserted= await _countriesService.UploadCountriesFromExcelFile(excelfile);

      ViewBag.Message = $"{countriesCountInserted} Countries Uploaded";
      return View();
    }
  }
}

ConnectFlow.UI/Views/Countries/UploadFromExcel.cshtml
@{
  ViewBag.Title = "Upload Countries";
  ViewBag.CurrentUrl = "~/Countries/UploadFromExcel";
}

<div class="center-box">

  <form asp-controller="Countries" asp-action="UploadFromExcel" method="post" enctype="multipart/form-data">
  

    <span class="form-title">Upload countries from Excel file</span>
    <p class="form-paragraph">
      Choose an xlsx file
    </p>
    <label for="file-input" class="drop-container">
      <span class="drop-title">Drop files here</span>
      or
      <input type="file" name="excelFile" id="file-input">
    </label>

    <div class="text-red">@ViewBag.ErrorMessage</div>
    <div class="text-green">@ViewBag.Message</div>

    <div class="form-field flex">
      <input type="submit" value="Upload" class="btn btn-success w-100 p-2 mt-2" />
    </div>
  </form>
</div>

<script>
  const dropContainer = document.querySelector('.drop-container');
  const fileInput = document.getElementById('file-input');


  dropContainer.addEventListener('dragover', (e) => {
    e.preventDefault();
    dropContainer.classList.add('drag-active');
  });

  dropContainer.addEventListener('dragleave', () => {
    dropContainer.classList.remove('drag-active');
  });

  dropContainer.addEventListener('drop', (e) => {
    e.preventDefault();
    dropContainer.classList.remove('drag-active');

    if (e.dataTransfer.files.length) {
      fileInput.files = e.dataTransfer.files;
    }
  });
</script>